### ISSUE TITLE
gdscript.live - broken from 4.1-stable down

### ISSUE THREAD

**Issue by belzecue** [Bryce-Dixon/gdscript-live#10] opened 2024-11-30 05:34 UTC
Running the default:

```
func main():
	print("Hello world!")

```
4.2 output (works):
```
Godot Engine v4.2.stable.official.46dc27791 - https://godotengine.org
 
Hello world!

```

4.1-stable:
```
Godot Engine v4.1.stable.official.970459615 - https://godotengine.org
```

3.6-stable
```
Godot Engine v3.6.stable.official.de2f0f147 - https://godotengine.org
SCRIPT ERROR: Parse Error: Expected "func".
          at: GDScript::reload (res://bootstrap.gd:16)

```

**Comment by Bryce-Dixon** [comment] 2024-12-29 12:28
Thanks for calling this out.

I've known this has been broken basically since the rewrite to running scripts server-side; the issue is that `containers/base/bootstrap.gd` only works for 4.2 and above since it uses some 4.2 specific features and the functionality needs to be back-ported to earlier versions so there would be multiple bootstrap files (eg: `bootstrap-4.2.gd`, `boostrap-4.0.gd`, `boostrap-3.1.gd`, etc.) which are used by the different containers.

**Comment by Bryce-Dixon** [comment] 2024-12-29 12:28
(clicked the wrong button and closed by mistake)

**Comment by Bryce-Dixon** [comment] 2024-12-30 09:11
Tracked down the issue to the fact that static variables were only added in Godot 4.2, so the error is being generated from `static var` where `static func` was the only expected possibility previously.

I'm trying to rework `bootstrap.gd` to not need static variables or functions at all since it needs to be instantiated, anyway.

**Comment by Bryce-Dixon** [comment] 2024-12-30 10:19
Got everything working down to version 3.1.2-stable. I really tried to get 3.0.6-stable working as well, but its errors are just too cryptic for me to wrap my head around while keeping functionality *somewhat* consistent between different builds, so I'm going to cut it.
As of commit 611a00d, all of Godot 4 is fully supported and Godot 3 is supported down to 3.1.2-stable, but function profiling will only be supported for Godot 4 as the profiler functionality is based on Godot 4's `await` functionality and I can't for the life of me comprehend how it would be rewritten with Godot 3's `yield`.

**Closed by Bryce-Dixon** 2024-12-30 10:19 UTC
Labels: bug
